# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guidance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eguidance.proto\"\"\n\x0fGuidanceRequest\x12\x0f\n\x07program\x18\x01 \x01(\t\" \n\x10GuidanceResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x9a\x01\n\x13HealthCheckResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32<\n\x08Guidance\x12\x30\n\x05Guide\x12\x10.GuidanceRequest\x1a\x11.GuidanceResponse\"\x00\x30\x01\x32r\n\x06Health\x12\x32\n\x05\x43heck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse\x12\x34\n\x05Watch\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guidance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GUIDANCEREQUEST']._serialized_start=18
  _globals['_GUIDANCEREQUEST']._serialized_end=52
  _globals['_GUIDANCERESPONSE']._serialized_start=54
  _globals['_GUIDANCERESPONSE']._serialized_end=86
  _globals['_HEALTHCHECKREQUEST']._serialized_start=88
  _globals['_HEALTHCHECKREQUEST']._serialized_end=125
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=128
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=282
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=203
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=282
  _globals['_GUIDANCE']._serialized_start=284
  _globals['_GUIDANCE']._serialized_end=344
  _globals['_HEALTH']._serialized_start=346
  _globals['_HEALTH']._serialized_end=460
# @@protoc_insertion_point(module_scope)
